CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS chatrooms (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    owner BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users_chatrooms (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    chatroom_id BIGINT NOT NULL REFERENCES chatrooms(id) ON DELETE CASCADE, 
    PRIMARY KEY (user_id, chatroom_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    author BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room BIGINT NOT NULL REFERENCES chatrooms(id) ON DELETE CASCADE,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

